<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\Auth\AuthProvider::class,
    App\Providers\Clients\ClientsProvider::class,
    App\Providers\DraftWeeklyPlanTasks\DraftWeeklyPlanTasksProvider::class,
    App\Providers\DraftWeeklyPlans\DraftWeeklyPlansProvider::class,
    App\Providers\LineDependencies\LineDependenciesProvider::class,
    App\Providers\LineSkus\LineSkusProvider::class,
    App\Providers\Lines\LinesProvider::class,
    App\Providers\PackingMaterialTransactionItems\PackingMaterialTransactionItemsProvider::class,
    App\Providers\PackingMaterialTransactions\PackingMaterialTransactionsProvider::class,
    App\Providers\PackingMaterials\PackingMaterialsProvider::class,
    App\Providers\Permissions\PermissionProvider::class,
    App\Providers\Positions\PositionsProvider::class,
    App\Providers\RawMaterials\RawMaterialsProvider::class,
    App\Providers\SkuPackingMaterials\SkuPackingMaterialsProvider::class,
    App\Providers\SkuRawMaterials\SkuRawMaterialsProvider::class,
    App\Providers\Skus\SkusProvider::class,
    App\Providers\Timeouts\TimeoutsProvider::class,
    App\Providers\Users\UserPermissionProvider::class,
    App\Providers\Users\UserProvider::class,
    App\Providers\WeeklyPlanEmployees\WeeklyPlanEmployeesProvider::class,
    App\Providers\WeeklyPlanTaskObservations\WeeklyPlanTaskObservationsProvider::class,
    App\Providers\WeeklyPlanTasks\WeeklyPlanTasksProvider::class,
    App\Providers\WeeklyPlans\WeeklyPlansProvider::class,
];
